apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: datacenter
data:
  TIME_FREQ: "5"
---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: datacenter
  labels:
    app: time-check
spec:
  volumes:
    - name: log-volume
      emptyDir: {}
  containers:
    - name: time-check
      image: busybox:latest
      volumeMounts:
        - name: log-volume
          mountPath: /opt/dba/time
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true; do 
            date >> /opt/dba/time/time-check.log;
            sleep $TIME_FREQ;
          done 
