apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-11-18T16:32:38Z"
  labels:
    app: nginxsvc
  name: nginxsvc
  namespace: default
  resourceVersion: "38703"
  uid: 512e8636-4871-434a-9fa0-a185c43e9261
spec:
  clusterIP: 10.100.159.43
  clusterIPs:
  - 10.100.159.43
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxsvc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
